apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo
  template:
    metadata:
      name: argo-pod
      labels:
        app: argo
    spec:
      containers:
      - name: argo-con
        image: yeso1/web-argo:2
